project:
  type: website

website:
  site-url: https://mrcaseb.github.io/firestaley/
  title: "firestaley"
  twitter-card:
    creator: "@mrcaseb"
    title: "Chargers Please Fire Staley"
    description: "Countdown until the Chargers - hopefully - fire Brandon Staley"
    card-style: "summary_large_image"
  open-graph:
    site-name: "Chargers Please Fire Staley"
    title: "Chargers Please Fire Staley"
    description: "Countdown until the Chargers - hopefully - fire Brandon Staley"

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

